spring.application.name=ride-config-server
# src/main/resources/application.properties

# serve on 8080
server.port=8080

# Git repo URL
spring.cloud.config.server.git.uri=https://github.com/go-cab-app/ride-config-server.git

# Pull from the 'develop' branch by default
spring.cloud.config.server.git.default-label=develop
